FROM oven/bun:1
WORKDIR /usr/src/app

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

COPY package.json bun.lock turbo.json ./
COPY packages ./packages
COPY apps/backend ./apps/backend

RUN bun install
RUN bun run db:generate

EXPOSE 8080
CMD ["bun", "run", "start:backend"]